---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hotelsunplaza/torvotools.com/
    - /bin/rm -rf $DEPLOYPATH/portal/assets
    - /bin/mkdir -p $DEPLOYPATH/portal/assets
    - /bin/cp -rf ./* $DEPLOYPATH
